### ISSUE TITLE
Request: Easylist Adult adservers as hosts file?

### ISSUE THREAD

**Issue by G-D-B-9-9** [ProgramComputer/Easylist_hosts#5]
To block those adult advertisers 

https://github.com/easylist/easylist/blob/master/easylist_adult/adult_adservers.txt

**Comment by ProgramComputer** [comment]
@G-D-B-9-9 Take a look at https://github.com/ProgramComputer/Easylist_hosts/tree/main/EasyListMirror/easylist_adult or https://github.com/ProgramComputer/Easylist_hosts/tree/main/EasyList_noadult
